Create CRUD operations.
oyhpnayiaw-as-micronaut/todolist-webpack pull request #2
Opened 2023-01-18 20:18 UTC by educationeb

- [x] Create, Read, Update, Delete methods for todo tasks.
- [x] Save todo tasks to localStorage when todo tasks is update.
- [x] Reset index values when todo tasks is update.

2023-01-18 21:34 UTC, cynthiainga requested changes
Hi @oyhpnayiaw, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://user-images.githubusercontent.com/80612925/157397398-00904e26-60ec-46cd-9510-240661c250ef.gif)

## Highlights

- [ ] No linters errors ✔️ 
- [ ] Descriptive PR ✔️ 
- [ ] Correct Github flow ✔️ 

## Required Changes ♻️

- [ ] Please kindly check the comments under the review 👇 👇 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-18 21:34 UTC, cynthiainga commented on src/TODO.js
> +    const task = { index: this.#tasks.length, description, completed: false };
- [ ] The property index should be set to the value of the new array length (i.e. if a 4th task is added to the list, the index of that task should equal to 4) which means the index should start by 1,2,3,..., please kindly fix that 🙃 🙃 

<img width="445" alt="Screen Shot 2023-01-19 at 00 09 34" src="https://user-images.githubusercontent.com/74501523/213298307-0f1dc779-d705-41ca-bf53-4846f5478060.png">

2023-01-19 04:10 UTC, t-yanick approved these changes
Hi @oyhpnayiaw , 

### Great job !!!
### To Highlight! :clap:  :green_circle: 

:heavy_check_mark:  Good commit messages
:heavy_check_mark: Descriptive Readme file

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:  
Congratulations! 🎉 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-19 04:59 UTC, merged

2023-01-19 08:15 UTC, oyhpnayiaw commented on src/TODO.js
> +   * @param {number} index - primary key of the task
Hi @t-yanick , thank you for taking the time to review my code. I understand your suggestion to remove commented code, but I wanted to clarify that the commented code in question is actually documentation.

Creating documentation for our code is important because it helps to explain the intent and function of the code, making it easier for other developers to understand and maintain. 

I understand the importance of keeping the codebase clean and professional. I will make sure to keep the documentation clear and concise. Thank you again for taking the time to review my code.